### ISSUE TITLE
Export to formats like pdf, doc, etc

### ISSUE THREAD

**Issue by anadirov** [jxlsteam/jxls#119]

**Comment by SoltauFintel** [comment]
@anadirov Do you want to develop this feature? If not I guess we will close this ticket with wontfix.

**Comment by anadirov** [comment]
@SoltauFintel I would be glad to try! I will use my main account https://github.com/basuha

**Comment by SoltauFintel** [comment]
In our company, we also thought about whether it would be possible to export an Excel file to a PDF. The problem is that you have to define what should go on one page and what should go on the next page. I think that's problematic. And there is not really a Java technology to export an XLSX into a PDF.

What are your plans? I think a concept should be written before programming.

And by the way, the repo owner @leonate  should also decide whether he would like to have such a feature in the core lib (or an additional sub project=jar).

**Comment by leonate** [comment]
I had this idea of exports to multiple formats long time ago. At that time there was no good enough java libraries / technologies to do it. But I suppose it might have changed since that time. 
But I am not sure if extending jxls-core would be a right way to do it, I guess it will depend on the overall architecture / concept of this feature. So I'd say some proof-of-concept would be needed to decide if it fits the existing architecture, or rather be a separate thing.

**Comment by SoltauFintel** [comment]
No action since March. Reopen if needed.
