### ISSUE TITLE
monoproject

### ISSUE THREAD

**Issue by SoltauFintel** [jxlsteam/jxls#2]
- We have only a POI implementation, so move the code to the jxls project. We will separate core from POI using different packages. A possible other implementation could be in a separate project.
- If you built in a core feature and wanted to test it with an Excel file, the test case always had to be in jxls-poi. I found that unfavorable.
- docs in same repo. It's important to use a github-capable solution (folder "/docs").

PROS and CONS

- PRO: If you edit a ticket it's easier to also update changes.md
- PRO: If somebody clones the repo he gets also the docs. Somebody who just need the JAR (with sources) would not clone and will use Maven-central.
- PRO: one JAR, one version
- CONTRA: **users must remove jxls-poi**

**Comment by leonate** [comment]
I am not convinced we should combine jxls and jxls-poi into a single module.
The original architecture was built on the idea to have a clear separation between the interface / core part (jxls) and the actual Java->Excel implementation (e.g jxls-poi). 
It may seem that it does not make sense since we have a single implementation jxls-poi only. But on the other hand any user of the library can create his own implementation of jxls interfaces based on any Java->Excel library and I don't feel comfortable ignoring this option.

**Comment by SoltauFintel** [comment]
Okay, we don't merge jxls and jxls-poi. Which jxls-site files habe to be transfered to Github?

**Comment by SoltauFintel** [comment]
Info by @leonate : "docroot can be removed, the only needed files are src folder and the pom.xml"
