### ISSUE TITLE
Whether the Headers and Data of Grid Command can take variables instead of context

### ISSUE THREAD

**Issue by Jamel-jun** [jxlsteam/jxls#288]
<img width="527" alt="image" src="https://github.com/jxlsteam/jxls/assets/50609931/30ee1cc2-95b5-4b24-8ad2-1af9f99431c1">
such as.
<img width="2010" alt="image" src="https://github.com/jxlsteam/jxls/assets/50609931/e18a45ef-cf51-479e-995b-1abd3408b81a">
How should I achieve

**Comment by SoltauFintel** [comment]
From the new (not online yet) Jxls 3.0 docs:

`headers`: expression where the result can be an array or an Iterable. Result null would create a grid with 0 columns. The array/Iterable item will be put as a value to the data map using the var name "header". It's usually a String. See example 4.

`data`: expression where the result can be an array or an Iterable. Result null would create a grid with 0 rows. The array/Iterable item is an array, Iterable or an object. If it's an object you have also to specify props. Otherwise the values of the array/Iterable will be output column by column using the cell var. See examples 1 to 3.

...

Example 4: adding headers to the context
```
context.putVar("headers", Arrays.asList("Name", "Birthday", "Payment"));
```

---

In jx: commands you can't write ${...}. Just write data="expression" or headers="expression".

**Comment by Jamel-jun** [comment]
When will it be released?

**Comment by SoltauFintel** [comment]
You can already use this feature.There's no date for v3.
-------- Ursprüngliche Nachricht --------Von: Jamel-jun ***@***.***> Datum: 24.12.23  13:11  (GMT+01:00) An: jxlsteam/jxls ***@***.***> Cc: SoltauFintel ***@***.***>, State change ***@***.***> Betreff: Re: [jxlsteam/jxls] Whether the Headers and Data of Grid Command can take variables instead of context (Issue #288) 
When will it be released?

**Comment by Jamel-jun** [comment]
<img width="1748" alt="image" src="https://github.com/jxlsteam/jxls/assets/50609931/872bb0a9-53eb-4cb0-9fb8-c3d837e0c282">
Thank you for your answer.
I have upgraded to 2.14.0, I still can't use it like this. Is there still a problem with my usage?

**Comment by SoltauFintel** [comment]
Looks quite good. How does your Java code look like? You could try `lastCell="T2" areas=["T2:T2","T3:T3"]`. Is your jx:grid part of a jx:each? (I don't know if that will work.) If so you could better use jx:each(direction="RIGHT") instead...

You could debug GridCommand.applyAt().
