### ISSUE TITLE
CellDataUpdater - How can I overwrite the cell value?

### ISSUE THREAD

**Issue by cwiechmann** [jxlsteam/jxls#43]
I have a question concerning the functionality of the CellDataUpdater. I have implemented an updater, but for any reason the CellData value isn't updated. Perhaps I have a misunderstanding and what I would like to achieve is not possible.

I would like to set/update the value of my cell to a new value, hence I was thinking the CellDataUpdater is the best choice. With this very simplified example I expected to see "HELLO" in the cells using that updater, but unfortunately not:

```java
@Override
public void updateCellData(CellData cellData, CellRef targetCell, Context context) {
	System.out.println("Updater is working....");
	cellData.setEvaluationResult("HELLO");
}
```
The cells, using that updater, are part of a each command. I see the code is really executed.

If this is not the best approach, what would you suggest? I have a data collection and I do prefer for some reasons to not change that collection upfront before handing it over. Instead adjust the Excel-Processing.

**Comment by leonate** [comment]
I would say CellDataUpdater should work unless there is a bug in Jxls.
Would you be able to produce a simple example demonstrating the problem so that I could run and debug it?
As an example see how tests in https://github.com/jxlsteam/jxls/tree/master/jxls-poi/src/test/java/org/jxls/templatebasedtests are constructed or check the examples (e.g. https://github.com/jxlsteam/jxls/blob/master/jxls-poi/src/test/java/org/jxls/examples/UpdateCellDemo.java).

**Comment by cwiechmann** [comment]
Thanks for coming back to me on this. However, I have decided not to generate an Excel spreadsheet. Hence the issue is not relevant anymore for me.
