### ISSUE TITLE
Support for java.time classes 

### ISSUE THREAD

**Issue by mstachniuk** [jxlsteam/jxls#77]
Since [apache-poi 4.1.1](https://poi.apache.org/changes.html) supports new Java date/time API added in Java 8, then jxls should also suport LocalDateTime, LocalDate and other classes from java.time.* package. 

Currently when object passed to Each-Command contains a field of type java.util.Date then the value is stored as a date in Excel - it respects date format defined in Excel.
For java.time.* objects the toString() method is invoked and Excel formatting doesn't work.

**Comment by SoltauFintel** [comment]
see ticket https://bitbucket.org/leonate/jxls/issues/177/support-for-java-8-time-api in old BitBucket system

**Comment by wagnerluis1982** [comment]
I can work on this issue, if possible :-)

**Comment by SoltauFintel** [comment]
@wagnerluis1982  For me it's okay. 👍🏻

**Comment by wagnerluis1982** [comment]
Hi, I've been checking the code today in order to understand how to add my contribution. I have a few questions.

1. Should I add Spock groovy-based tests or JUnit tests?
2. Test class names should match issue number? Or I can come up with more intuitive names?
3. Upgrade any depending libraries can be part of the solution?

If I should go tests in JUnit, could you tell me if:
1. JUnit 4 or 5?
2. Do you use any fancy test libs such as AssertJ?

**Comment by SoltauFintel** [comment]
A1) Please use JUnit. Please do not use Spock/Groovy. We want to get rid of those Spock/Groovy tests and want to convert to JUnit/Java, but it's so much work.

A2) You can use a more intuitive class name. The template file should have the same name.

A3) On the one hand it would be good if we discussed this beforehand, on the other hand your activity should not be unnecessarily delayed. Is it just a Nice-to-have or a Must?

B1) JUnit 4. I guess a switch to v5 is a ticket itself. Will still everything work after switching and does it have benefits?

B2) No, we don't. I don't know AssertJ and so I have no opinion what to say at the moment.

I think it's a good way to focus on the core problem.

**Comment by wagnerluis1982** [comment]
Thanks for the swift answer.

A1) I'd love to understand some decisions, such as abandon Spock (I normally see the opposite), but it's subject for another conversation.

A3) Right now I don't know for sure, since I didn't properly start yet. I'd like to know prior what are my options.

B1) It's opinionated which JUnit version to use. In general lines, the tests are the same, but JUnit has easier ways to do things, like parameterized tests.

B2) AssertJ gives a boost on JUnit's assertion methods. Test assertions are more expressive and less verbose. It's a library not a test framework. It's still JUnit!

Now, let me start to code :-)

**Comment by SoltauFintel** [comment]
Thank you for your PR. Looks good.

How do you feel about supporting ZonedDateTime? Does it make sense? In our company we use time zones.

**Comment by wagnerluis1982** [comment]
> How do you feel about supporting ZonedDateTime? Does it make sense? In our company we use time zones.

Well, in general, technically speaking, it's not such a big deal, given the target date-time be simply the result of `toLocalDateTime()`

However, if you're talking about **jxls** to do any timezone shifts before write to the cell, then, a little design is needed to answer the questions:
- Where the target timezone will come from?
- How would looks like this configuration setting, just number of +/- hours? Or a string representation of the timezone?

**Comment by SoltauFintel** [comment]
Instead of a LocalDateTime, someone could also supply a ZonedDateTime. I don't want to think about the solution myself. It's your ticket. 😏  My suggestion would be that you incorporate this as you see fit. If someone does not get along with it, he can change that (in his local JXLS copy) or he writes a ticket.

**Comment by wagnerluis1982** [comment]
@SoltauFintel I see, I will add to the PR a basic support for `ZonedDateTime` (with no configurable time shifts).

BTW, I was thinking, does it makes sense to add support to other JSR310 types, such as `LocalTime`, `Instant`, `Clock`?

**Comment by wagnerluis1982** [comment]
@SoltauFintel I added the basic support to `ZonedDateTime`.

Right now it uses local timeze. I don't know if I will have time this week for enhance to be zone-configurable. If you're in a hurry, I can do as a future issue.

**Comment by SoltauFintel** [comment]
I'm not in a hurry. ;-)

Adding LocalTime would be good.

Instant, Clock - I don't know. You can decide.

**Comment by ertugrultabak** [comment]
@wagnerluis1982 @SoltauFintel 
What are the plans to release this PR?

**Comment by SoltauFintel** [comment]
I have to review that first... And then after the merge @leonate should have the time to create a release, if he even wants to (2.9.1-rc1 I guess). But you can also create a release yourself. Due to Corona, we don't work so much on JXLS privately and therefore everything takes longer.
